name: Déploiement et validation des métadonnées 

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4  
        with:
          fetch-depth: 0  

      - name: Utiliser Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installer SFDX CLI et le plugin sfdx-git-delta
        run: |
          npm install -g @salesforce/cli@latest
          echo "y" | sfdx plugins:install sfdx-git-delta 
    
      - name: 'Authentification Salesforce'
        run: |
          echo "${SERVER_KEY_PASSWORD}" > server.key
          sf auth jwt grant \
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --set-default-dev-hub \
            --alias vscodeOrg
        env:
          SERVER_KEY_PASSWORD: ${{ secrets.SERVER_KEY_PASSWORD }}  # Mot de passe clé stocké en secret dans gitHub

      
      - name: 'Générer le delta des métadonnées entre ce commit et le précédent'
        run: |
          sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output-dir .
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
      

     
      - name: 'Tester et Déployer les métadonnées sur la branche main'
        if: github.ref == 'refs/heads/main'
        run: sfdx project deploy start --manifest package/package.xml --test-level RunLocalTests --target-org vscodeOrg

