name: Deploy and Validate Metadata

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install SFDX CLI and sfdx-git-delta plugin # Ce package va vous permettre de faire un delta entre votre branche et la branch ciblé. Voici la documentation : https://github.com/scolladon/sfdx-git-delta
        run: |
          npm install -g @salesforce/cli@latest
          echo "y" | npm install -g sfdx-git-delta@3.3.0
          sf help

      - name: 'Authentification Salesforce' # Vous devez avoir une connexion avec Salesforce pour pouvoir deployer le code à la dernière étape.
        run: |
          echo "${SERVER_KEY_PASSWORD}" > server.key
          sf auth jwt grant \
          --client-id ${{ secrets.SF_CONSUMER_KEY }} \
          --jwt-key-file server.key \
          --username ${{ secrets.SF_USERNAME }} \
          --set-default-dev-hub \
          --alias vscodeOrg

        env:
         SERVER_KEY_PASSWORD: ${{ secrets.SERVER_KEY_PASSWORD }}
      - name: 'test Plugin'
        run: |
          sf plugins list

      - name: 'Generate metadata delta pull request'  # Utilisez le plug-in sfdx-git-delta pour effectuer un delta, generer le package xml dans un fichier temporaire ex : .temp
        run: |
          sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output.
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml

      - name: 'Déployer les métadonnées sur la branch main'
        if: github.ref == 'refs/heads/main'
        run:   force source deploy -x package/package.xml -l RunLocalTests -u vscodeOrg
